const db = require("./connection");
const { Game } = require("../models");

const games = await Game.insertMany([
  {
    name: "A Link to the Past",
    description: "A Link to the Past",
    imgUrl: "/images/a-link-to-the-past-snes.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "Act Raiser",
    description: "Act Raiser",
    imgUrl: "/images/actraiser.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "Mario RPG",
    description: "Mario RPG",
    imgUrl: "/images/mario-rpg.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "Donkey Kong Country",
    description: "Donkey Kong Country",
    imgUrl: "/images/dk-country-snes.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "Earth Bound",
    description: "Earth Bound",
    imgUrl: "/images/eartbound.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "Final Fantasy VI",
    description: "Final Fantasy VI",
    imgUrl: "/images/ffv1-snes.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "F Zero",
    description: "F Zero",
    imgUrl: "/images/f-zero.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "Krono Trigger",
    description: "Krono Trigger",
    imgUrl: "/images/krono-trigger.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "Star Fox",
    description: "Star Fox",
    imgUrl: "/images/starfox.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "Street Fighter 2",
    description: "Street Fighter 2",
    imgUrl: "/images/street-fighter-2.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "Super Castlevania IV",
    description: "Super Castlevania IV",
    imgUrl: "/images/super-castlevania-iv.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "Super Mario World",
    description: "Super Mario World",
    imgUrl: "/images/super-mario-snes.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "Super Mario World 2 Yoshis Island",
    description: "Super Mario World 2 Yoshis Island",
    imgUrl: "/images/super-mario-world-2-yoshis-island.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "Teenage Mutant Ninja Turtles Turtles in Time",
    description: "Teenage Mutant Ninja Turtles Turtles in Time",
    imgUrl: "/images/tmnt-turtles-in-time.jpg",
    price: 20,
    category: "Super Nintendo",
    seller: "",
  },
  {
    name: "Bionic Commando",
    description: "Bionic Commando",
    imgUrl: "/images/Bionic-commando-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Castlevania II Simons Quest",
    description: "Castlevania II Simons Quest",
    imgUrl: "/images/Castlevania-III-Draculas-Curse.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Castlevania III Draculas Curse",
    description: "Castlevania III Draculas Curse",
    imgUrl: "/images/Castlevania-III-Draculas-Curse-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Contra",
    description: "Contra",
    imgUrl: "/images/Contra-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Dragon Warrior IV",
    description: "Dragon Warrior IV",
    imgUrl: "/images/Dragon-Quest-IV-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Ducktales",
    description: "Ducktales",
    imgUrl: "/images/DuckTales-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Excitebike",
    description: "Excitebike",
    imgUrl: "/images/Excitebike-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Final Fantasy",
    description: "Final Fantasy",
    imgUrl: "/images/Final-Fantasy-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Ghosts n Goblins",
    description: "Ghosts n Goblins",
    imgUrl: "/images/Ghosts-n-Goblins-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Kirby's Adventure",
    description: "Kirby's Adventure",
    imgUrl: "/images/Kirby's-Adventure-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "MegaMan 2",
    description: "MegaMan 2",
    imgUrl: "/images/Mega-man-2.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Metroid",
    description: "Metroid",
    imgUrl: "/images/Metroid-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Mike Tysons Punch Out!!",
    description: "Mike Tysons Punch Out!!",
    imgUrl: "/images/Mike-Tyson's-Punch-Out!!-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Ninja Gaiden",
    description: "Ninja Gaiden",
    imgUrl: "/images/Ninja-Gaiden-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Super Mario Bros 3",
    description: "Super Mario Bros 3",
    imgUrl: "/images/Metroid-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Super Mario Bros",
    description: "Super Mario Bros",
    imgUrl: "/images/Super-Mario-Bros-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Tetris",
    description: "Tetris",
    imgUrl: "/images/Tetris-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "The Legend of Zelda",
    description: "The Legend of Zelda",
    imgUrl: "/images/The-Legend-of-Zelda-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Metroid",
    description: "Metroid",
    imgUrl: "/images/Metroid-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Metroid",
    description: "Metroid",
    imgUrl: "/images/Metroid-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
  {
    name: "Metroid",
    description: "Metroid",
    imgUrl: "/images/Metroid-nes.jpg",
    price: 20,
    category: "Nintendo",
    seller: "",
  },
]);
